server:
  host: 0.0.0.0
  port: 9091

log:
  level: info

jwt_secret: YOUR_JWT_SECRET
session_secret: YOUR_SESSION_SECRET
default_redirection_url: https://yourdomain.com

totp:
  issuer: yourdomain.com
  period: 30
  skew: 1

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 1024
