services:
  authelia:
    container_name: authelia
    image: docker.io/authelia/authelia:latest
    restart: unless-stopped
    labels:
      glance.name: Authelia
      glance.icon: di:authelia
      glance.url: https://auth.m3v.dev
      glance.description: authentication and 2fa
      glance.category: security
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: /secrets/JWT_SECRET
      AUTHELIA_SESSION_SECRET_FILE: /secrets/SESSION_SECRET
      AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE: /secrets/STORAGE_PASSWORD
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: /secrets/STORAGE_ENCRYPTION_KEY
    volumes:
      - D:\srv\docker\authalia\config:/config
      - D:\srv\docker\authalia\secrets:/secrets
    depends_on:
      - caddy
    ports:
      - 9091:9091
    networks:
      - net

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    labels:
      glance.name: Vaultwarden
      glance.icon: di:bitwarden
      glance.url: https://vault.m3v.dev
      glance.description: password manager
      glance.category: security
    environment:
      DOMAIN: "https://vault.m3v.dev"
    volumes:
      - D:\srv\vaultwarden:/data
    ports:
      - 80:80
    depends_on:
      - caddy
    networks:
      - net