services:
# media services
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    labels:
      glance.name: Sonarr
      glance.icon: di:sonarr
      glance.url: https://sonarr.m3v.dev
      glance.description: TV-Show manager
      glance.category: media
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\sonarr:/config
      - E:\anime3:/anime3
      - G:\anime2:/anime2
      - D:\srv\media\anime:/anime
      - D:\srv\media\downloads:/downloads
    depends_on:
      - caddy
    ports:
      - 8989:8989
    networks:
      net:
        ipv4_address: 172.25.0.18

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    labels:
      glance.name: Radarr
      glance.icon: di:radarr
      glance.url: https://radarr.m3v.dev
      glance.description: Movie manager
      glance.category: media
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\radarr:/config
      - E:\movies3:/movies3
      - G:\movies2:/movies2
      - D:\srv\media\movies:/movies
      - D:\srv\media\downloads:/downloads
    depends_on:
      - caddy 
    ports:
      - 7878:7878
    networks:
      net:
        ipv4_address: 172.25.0.17

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    labels:
      glance.name: Qbittorrent
      glance.icon: di:qbittorrent
      glance.url: https://qbit.m3v.dev
      glance.description: torrent client
      glance.category: media
    environment:
    - TZ=Europe/Amsterdam
    - WEBUI_PORT=8080
    - TORRENTING_PORT=6881
    volumes:
      - D:\srv\qbit:/config
      - D:\srv\media\downloads:/downloads
    depends_on:
      - caddy
      - gluetun
    network_mode: "service:gluetun"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    labels:
      glance.name: Prowlarr
      glance.id: prowlarr
      glance.icon: di:prowlarr
      glance.url: https://prowlarr.m3v.dev
      glance.description: indexer manager
      glance.category: media
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\prowlarr:/config
    depends_on:
      - caddy
      - gluetun
    network_mode: "service:gluetun"

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr:latest
    container_name: recyclarr
    restart: unless-stopped
    labels:
      glance.name: Recyclarr
      glance.icon: di:recyclarr
      glance.description: management for media quality profiles
      glance.category: media
    environment:
      - TZ=Europe/Amsterdam
      - NOTIFIARR_API_KEY=${NOTIFIARR_API_KEY}
    volumes:
      - D:\srv\recyclarr:/config
    depends_on:
      - sonarr
      - radarr
    networks:
      net:
        ipv4_address: 172.25.0.16
  
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    labels:
      glance.name: Jellyfin
      glance.icon: di:jellyfin
      glance.url: https://jellyfin.m3v.dev
      glance.description: media docker
      glance.category: media
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\jellyfin:/config
      - D:\srv\jellyfin\cache:/cache
      - E:\anime3:/anime3
      - G:\anime2:/anime2
      - D:\srv\media\anime:/anime
      - E:\movies3:/movies3
      - G:\movies2:/movies2
      - D:\srv\media\movies:/movies
    depends_on:
      - caddy
    ports:
      - 8096:8096
      - 7359:7359/udp
    networks:
      net:
        ipv4_address: 172.25.0.14

# manga services
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:latest
    container_name: suwayomi
    restart: unless-stopped
    labels:
      glance.name: Suwayomi
      glance.icon: di:suwayomi
      glance.url: https://suwayomi.m3v.dev
      glance.description: Manga reader and manager
      glance.category: media
    environment:
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json","https://raw.githubusercontent.com/suwayomi/tachiyomi-extension/repo/index.min.json"]
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\media\manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - D:\srv\suwayomi:/home/suwayomi/.local/share/Tachidesk
    depends_on: 
      - caddy 
    ports:
      - 4567:4567
    networks:
      net:
        ipv4_address: 172.25.0.13

  komga:
    image: ghcr.io/gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    labels:
      glance.name: Komga

      glance.icon: di:komga
      glance.url: https://komga.m3v.dev
      glance.description: Manga reader
      glance.category: manga
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\komga:/config
      - D:\srv\media\manga:/books
    depends_on:
      - caddy
    ports:
      - 25600:25600
    networks:
      net:
        ipv4_address: 172.25.0.12

  komf:
    image: sndxr/komf:latest
    container_name: komf
    restart: unless-stopped
    labels:
      glance.name: Komf
      glance.icon: di:komga
      glance.description: Manga reader companion app for Komga
      glance.category: manga
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      - D:\srv\komf:/config
    depends_on:
      - komga
    ports:
      - 8085:8085
    networks:
      net:
        ipv4_address: 172.25.0.11

# password management
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    labels:
      glance.name: Vaultwarden
      glance.icon: di:bitwarden
      glance.url: https://vault.m3v.dev
      glance.description: password manager
      glance.category: security
    environment:
      DOMAIN: "https://vault.m3v.dev"
    volumes:
      - D:\srv\vaultwarden:/data
    ports:
      - 80:80
    depends_on:
      - caddy
    networks:
      net:
        ipv4_address: 172.25.0.9

# web servers
  glance:
    container_name: glance
    image: glanceapp/glance:latest
    restart: unless-stopped
    labels:
      glance.name: Glance
      glance.id: glance
      glance.icon: di:glance
      glance.url: http://glance.m3v.dev
      glance.description: selfhosted dashboard
      glance.category: dashboard
    volumes:
      - D:\srv\docker\glance\glance.yml:/app/config/glance.yml
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    ports:
      - 9080:9080
    depends_on:
      - caddy
    networks:
      net:
        ipv4_address: 172.25.0.8
  
  glances-ical-api:
    image: ghcr.io/awildleon/glance-ical-events:latest
    container_name: glances-ical-api
    restart: unless-stopped
    labels:
      glance.name: Glance-ical-api
      glance.icon: di:google calendar
      glance.url: http://glance.m3v.dev
      glance.description: selfhosted dashboard ical api
      glance.category: dashboard
      glance.parent: glance
    ports:
      - 8076:8076
    networks:
      net:
        ipv4_address: 172.25.0.7


# network and vpn services
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    labels:
      glance.name: Caddy
      glance.icon: di:caddy
      glance.description: reverse-proxy and automatic ssl
      glance.category: network
    volumes:
      - D:\srv\docker\caddy\Caddyfile:/etc/caddy/Caddyfile
      - D:\srv\docker\caddy\data:/data
      - D:\srv\docker\caddy\config:/config
      - D:\srv\docker\caddy\cloudflare-origin-cert\:/cloudflare-origin-cert
    ports:
      - 443:443
      - 2025:2025
    networks:
      net:
        ipv4_address: 172.25.0.6

  gluetun:
    image: qmcgaw/gluetun:latest
    container_name: gluetun
    restart: unless-stopped
    labels:
      glance.name: Gluetun
      glance.icon: di:gluetun
      glance.description: vpn client
      glance.category: network
    cap_add:
        - NET_ADMIN
    devices:
        - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=openvpn
      - OPENVPN_USER=${OPENVPN_USER}
      - OPENVPN_PASSWORD=m
      - OPENVPN_CUSTOM_CONFIG=/gluetun/mullvad_nl_ams.ovpn
      - TZ=Europe/Amsterdam
    volumes:
    - D:\srv\openvpn:/gluetun
    healthcheck:
      test: ["CMD", "wget", "-qO", "-", "https://ipinfo.io/ip"]
      interval: 30s
      retries: 3
    ports:
      - 9696:9696
      - 8191:8191
      - 8080:8080
      - 6881:6881/udp
      - 6881:6881/tcp
    networks:
      net:
        ipv4_address: 172.25.0.4

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    labels:
      glance.name: FlareSolverr
      glance.icon: di:cloudflare
      glance.description: bypass cloudflare protections
      glance.category: network
      glance.parent: prowlarr
    environment:
      - LOG_LEVEL=info
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Amsterdam
    depends_on:
      - radarr
      - sonarr
      - prowlarr
      - gluetun
    network_mode: "service:gluetun"

# management services
  dockge:
    image: louislam/dockge:latest
    container_name: dockge
    restart: unless-stopped
    labels:
      glance.name: Dockge
      glance.icon: di:dockge
      glance.url: http://dockge.m3v.dev
      glance.description: docker gui management
      glance.category: management
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true
      - TZ=Europe/Amsterdam
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/host/d/srv/docker:/opt/stacks
      - D:\srv\dockge:/app/data
    depends_on:
      - caddy
    networks:
      net:
        ipv4_address: 172.25.0.3

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped  
    labels:
      glance.name: Watchtower
      glance.icon: di:watchtower
      glance.description: automatic docker container updates
      glance.category: management   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 300 --cleanup
    networks:
      net:
        ipv4_address: 172.25.0.2

# volume and network definitions
networks:
  net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/24
          gateway: 172.25.0.1
    attachable: true
