komga:
  baseUri: http://komga:25600 
  komgaUser: max@m3v.dev 
  komgaPassword: komgaED3M6S8e
  eventListener:
    enabled: true
    metadataLibraryFilter: [ ]
    metadataSeriesExcludeFilter: [ ]
    notificationsLibraryFilter: [ ]
  metadataUpdate:
    default:
      libraryType: "MANGA"
      updateModes: [ API ]
      aggregate: true
      mergeTags: true
      mergeGenres: true
      bookCovers: true
      seriesCovers: true
      overrideExistingCovers: true
      overrideComicInfo: false
      postProcessing:
        seriesTitle: true
        seriesTitleLanguage: "en"
        fallbackToAltTitle: true
        alternativeSeriesTitles: false
        alternativeSeriesTitleLanguages:
          - "en"
          - "ja-ro"
        orderBooks: true
        scoreTagName: "score"

database:
  file: ./komf.sqlite

metadataProviders:
  malClientId: "71acf4a77c1bafa52211818d3e8dac9c37d1d957643e938cff1be1d00f3cab71"
  defaultProviders:
    mangaUpdates:
      priority: 10
      enabled: true
      mediaType: "MANGA"
      authorRoles: [ "WRITER" ]
      artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ]
      seriesMetadata:
        thumbnail: true
    mal:
      priority: 45
      enabled: true
      mediaType: "MANGA"
    aniList:
      priority: 15
      enabled: true
      mediaType: "MANGA"
      tagsScoreThreshold: 60
      tagsSizeLimit: 20
    yenPress:
      priority: 40
      enabled: true
      mediaType: "MANGA"
    kodansha:
      priority: 60
      enabled: true
    bookWalker:
      priority: 20
      enabled: true
      mediaType: "MANGA"
    mangaDex:
      priority: 65
      enabled: true
      coverLanguages:
        - "en"
        - "ja"
    hentag:
      priority: 100
      enabled: true

server:
  port: 8085

logLevel: INFO