services:
  suwayomi:
    image: ghcr.io/suwayomi/tachidesk:latest
    container_name: suwayomi
    restart: unless-stopped
    labels:
      glance.name: Suwayomi
      glance.icon: di:suwayomi
      glance.url: https://suwayomi.m3v.dev
      glance.description: Manga reader and manager
      glance.category: media
    environment:
      - EXTENSION_REPOS=["https://raw.githubusercontent.com/keiyoushi/extensions/repo/index.min.json","https://raw.githubusercontent.com/suwayomi/tachiyomi-extension/repo/index.min.json"]
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\docker\media\manga:/home/suwayomi/.local/share/Tachidesk/downloads
      - D:\srv\docker\data\suwayomi:/home/suwayomi/.local/share/Tachidesk
    depends_on: 
      - caddy 
    ports:
      - 4567:4567
    networks:
      - net

  komga:
    image: ghcr.io/gotson/komga:latest
    container_name: komga
    restart: unless-stopped
    labels:
      glance.name: Komga

      glance.icon: di:komga
      glance.url: https://komga.m3v.dev
      glance.description: Manga reader
      glance.category: manga
    environment:
      - TZ=Europe/Amsterdam
    volumes:
      - D:\srv\docker\data\komga:/config
      - D:\srv\docker\media\manga:/books
    depends_on:
      - caddy
    ports:
      - 25600:25600
    networks:
      - net

  komf:
    image: sndxr/komf:latest
    container_name: komf
    restart: unless-stopped
    labels:
      glance.name: Komf
      glance.icon: di:komga
      glance.description: Manga reader companion app for Komga
      glance.category: manga
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+UnlockExperimentalVMOptions -XX:+UseShenandoahGC -XX:ShenandoahGCHeuristics=compact -XX:ShenandoahGuaranteedGCInterval=3600000 -XX:TrimNativeHeapInterval=3600000
    volumes:
      - D:\srv\docker\server\komf:/config
    depends_on:
      - komga
    ports:
      - 8085:8085
    networks:
      - net
